<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIEd4dwQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIEd4dwQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIEd4dwQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIEd4dwQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIEd4dwQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'IEd4dwQ',
    'container.build_id' => 'abb7e1ca',
    'container.build_time' => 1583082879,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIEd4dwQ');
